version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
        ports:
            - "9000:9000"
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: nginx_webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=news_aggregator
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
